feat(devcontainer): devcontainer and easy up robot
Opentrons/opentrons-emulation pull request #193
Opened 2022-10-04 16:14 UTC by y3rsh

# Overview

- Add devcontainer
- Use devcontainer and docker-compose to bring up a robot with one command

- [ ] Where `make setup` ?
- [ ] Test compose
- [ ] remove this branch from `build-devcontainer.yaml`
- [ ] add documentation

2022-10-04 16:20 UTC, DerekMaggio commented
> Where `make setup` ?

I would put it in the top level Makefile under `dev-container` or `vs-code-container` or something like that

2022-10-04 21:55 UTC, y3rsh commented on emulation_system/Makefile
>  .PHONY: setup
@DerekMaggio this change cool?

2022-10-04 21:56 UTC, y3rsh commented on Makefile
> +RUN_COMMAND := $(if $(CI),remove-build-run-detached,remove-build-run)
- [ ] @y3rsh remove this.

2022-10-04 21:57 UTC, y3rsh commented on Makefile
> +COMPOSE_RUN_COMMAND := docker-compose -f - up --remove-orphans
@DerekMaggio this ok?

2022-10-04 21:58 UTC, y3rsh commented on .github/workflows/build-devcontainer.yaml
> +      - "233-devcontainer" # remove before merge
- [ ] remove this line before merge

```suggestion
```

2022-10-04 21:59 UTC, y3rsh commented
- [ ] @y3rsh create docs

2022-10-05 14:27 UTC, DerekMaggio commented on emulation_system/Makefile
>  .PHONY: setup
Yes sir

2022-10-05 14:27 UTC, DerekMaggio commented on Makefile
> +COMPOSE_RUN_COMMAND := docker-compose -f - up --remove-orphans
Yeah, I don't see why not. Should just make everything start cleaner. 
If it ends up causing problems down the line we can just remove it.

2022-10-05 14:35 UTC, DerekMaggio reviewed
Everything looks good!
Just some questions I have before approving.

2022-10-05 14:35 UTC, DerekMaggio commented on .github/workflows/build-devcontainer.yaml
> +            python --version
What is this `runCmd` for?

2022-10-05 14:35 UTC, DerekMaggio commented on scripts/docker_convenience_scripts/in_docker.py
> +import os
What is this?

2022-10-05 15:00 UTC, y3rsh commented on .github/workflows/build-devcontainer.yaml
> +            python --version
[That is the parameter of what command to run **in** the container once the container is up.  Here we don't need to run anything, so I am printing python version.](https://github.com/devcontainers/ci/blob/main/docs/github-action.md#inputs)

You could run `make setup` then `make lint` and do your lint check.

This part is still a bit clunky...  It is good for simple things but more complex things would not be fun at the current maturity.

2022-10-05 15:07 UTC, y3rsh commented on scripts/docker_convenience_scripts/in_docker.py
> +import os
Detecting if you are running inside a docker container is tricky.  This script returns a string of `true` or `false`
We are using the output to determine the hostname.  When you are in a container (docker-from-docker) and then spin up container(s) on the host, like we are doing in the devcontainer, you cannot get to it from `localhost` from inside the devcontainer.  You need  `host.docker.internal`.  BUT the app on the host system would be able to resolve `localhost`.

2022-10-05 20:42 UTC, y3rsh commented
Video for readme
https://user-images.githubusercontent.com/502770/194157913-316e8115-2ff4-4658-a274-8b22f2bdef5c.mp4

2022-10-05 20:49 UTC, y3rsh commented
Dev container build done image.
![image](https://user-images.githubusercontent.com/502770/194160391-b4113217-1357-44a5-adf2-82c46abb1bbb.png)
![image](https://user-images.githubusercontent.com/502770/194160726-8e2063b2-124d-4029-ab48-600cf845d175.png)

2022-10-05 20:58 UTC, y3rsh commented
Set localhost in app

https://user-images.githubusercontent.com/502770/194162290-48c370f9-2b1b-4a75-995b-d6f1dc2e39bb.mp4

2022-10-05 21:25 UTC, y3rsh commented on Makefile
> +	curl -s --location --request GET 'http://$(ROBOT_HOST):31950/modules' --header 'opentrons-version: *' | json_pp -json_opt pretty,canonical
- Added the docs.
- Yes, useful samples as of now.  Need 
  - ot3 with modules when we get there
  - ot2 switch in Gen2 Thermocycler in the all_modules sample
- a user would have to have make on thier host system
  - not sure if possible
  - just as easy to open a new window of vs code and use the command palette, I can make a video of that.

2022-10-06 14:54 UTC, DerekMaggio approved these changes
Looks fantastic to me!
So excited for this!

2022-10-06 18:50 UTC, DerekMaggio requested changes

2022-10-06 18:50 UTC, DerekMaggio commented on .github/workflows/build-devcontainer.yaml
> -    branches:
Why are we not building against main anymore?

2022-10-06 19:09 UTC, merged