E2e tests
Opentrons/opentrons-emulation pull request #240
Opened 2023-02-17 20:29 UTC by DerekMaggio

# Overview

# Changelog

# Review requests

# Risk assessment

2023-02-27 16:46 UTC, sfoster1 requested changes
First off, this is awesome - great structure, love all the stuff to prevent the fast-fail, great work.

I think that we can remove some of the pytest workarounds with just a little more work.
Fundamentally, the thing we want to do is
- For each type of configuration
   -  check everything about it every time

That reads to me like everything we check being a separate pytest test - all tests run every time, regardless of whether other tests fail.

Now that's a lot of tests, and we don't really want to write them by hand, and we do want additional tests to be pretty easy to add. The right way to do this is probably with a [pytest hook](https://docs.pytest.org/en/7.2.x/reference/reference.html#std-hook-pytest_generate_tests), but that's pretty annoying, so I think the best thing might be to add yet another level of parametrization: you're already building the system test definitions in the fixtures, so have them emit tests for each thing they want to check.

2023-02-27 16:46 UTC, sfoster1 commented on .github/workflows/e2e-tests.yaml
> +      - '.github/workflows/e2e-tests.yaml' # Make sure to remove
IMO you should keep this, removing it makes it easy for a typo in here to fail things

2023-02-27 16:46 UTC, sfoster1 commented on emulation_system/tests/e2e/conftest.py
> +) -> Callable:
```suggestion
) -> Callable[[str], OT3Containers]:
```

2023-02-27 16:46 UTC, sfoster1 commented on emulation_system/tests/e2e/conftest.py
> +) -> Callable:
```suggestion
) -> Callable[[str], ModuleContainers]:
```

2023-02-27 16:46 UTC, sfoster1 commented on emulation_system/tests/e2e/conftest.py
> +) -> Callable:
```suggestion
) -> Callable[[str], ExpectedBindMounts]`:
```

2023-02-27 16:46 UTC, sfoster1 commented on emulation_system/tests/e2e/fixtures/module_containers.py
> +"""Dataaclass to easily access all module containers in system."""
```suggestion
"""Dataclass to easily access all module containers in system."""
```

2023-02-27 16:46 UTC, sfoster1 commented on emulation_system/tests/e2e/fixtures/module_containers.py
> +    hardware_emulation_thermocycler_modules: Optional[List[Container]]
Do we really need the `Optional` here? Can an empty list serve the purpose, or is there a difference in meaning between "empty list" and "list not specified"?

2023-02-27 16:46 UTC, sfoster1 commented on emulation_system/tests/e2e/fixtures/module_containers.py
> +        for mod_list in [
not using `Optional` would simplify this

2023-02-27 16:46 UTC, sfoster1 commented on emulation_system/tests/e2e/fixtures/ot3_containers.py
> +"""Module containg helper class to access OT-3 Containers for local system"""
```suggestion
"""Module containing helper class to access OT-3 Containers for local system"""
```

2023-02-27 16:46 UTC, sfoster1 commented on emulation_system/tests/e2e/fixtures/ot3_containers.py
> +    # but want to check that with an assert and not a type error
mmm IMO we really want to express that some other way, then. The types here should describe the state of the initialized dataclass, after all.

One thing we could do here, if we want to have the checking deferred, is separate "stuff we wanted to build a dataclass with" and "the dataclass we built from that stuff"; have a method that gets the second from the first; and have that method raise validation errors. The "arguments" dataclass captures whether the monorepo was specified or not; but the "values" dataclass lets dependent code use it without having to check every time.

2023-02-27 16:46 UTC, sfoster1 commented on emulation_system/tests/e2e/test_ot3_systems.py
> +    assert not test_def.is_failure(), test_def.print_output()
probably what this should be is
```python
if test_def.is_failure():
    pytest.fail(test_def.print_output(), pytrace=False)
```
(from [docs](https://docs.pytest.org/en/7.2.x/reference/reference.html#pytest-fail))
since just the assert will get a redundant and incorrect traceback.

2023-02-27 17:45 UTC, sfoster1 commented
> Now that's a lot of tests, and we don't really want to write them by hand, and we do want additional tests to be pretty easy to add. The right way to do this is probably with a [pytest hook](https://docs.pytest.org/en/7.2.x/reference/reference.html#std-hook-pytest_generate_tests), but that's pretty annoying, so I think the best thing might be to add yet another level of parametrization: you're already building the system test definitions in the fixtures, so have them emit tests for each thing they want to check.

Actually, a better way to do this might be to marshal everything involved into dicts and assert the dicts deep equality. That will give you everything you want: parallel non-blocking comparisons and nice diff output.

2023-03-06 18:40 UTC, DerekMaggio commented on .github/workflows/e2e-tests.yaml
> +      - '.github/workflows/e2e-tests.yaml' # Make sure to remove
So I totally screwed up here. 
1. `.github/workflows/e2e-tests.yaml` is for sure not a branch
2. If I add it to `push.paths` it will only run when it is one of those branches AND `.github/workflows/e2e-tests.yaml` has been modified. Github Action Docs for this [here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-affects-specific-files). This is not what I want. I want it to run on push to those branches only. 

The fix is to remove it from `branches` and leave it as a path in `pull_request`

2023-04-06 17:38 UTC, y3rsh approved these changes
Got a little glassy eyed about half way through.
I think we should add a make target that allows you to see what tests would run using  the `--collect-only` argument for pytest.  The output of that is a little hard to parse with parameterization but better than nothing.

2023-04-06 17:38 UTC, y3rsh commented on .github/workflows/yaml-sub-sanity-check.yaml
> +      - name: Get first sub value
What is a sub value?

2023-04-06 17:38 UTC, y3rsh commented on emulation_system/Makefile
> +	poetry run pytest tests/e2e -k "${test_id}"
```suggestion
	@poetry run pytest tests/e2e -k "${test_id}"
```

2023-05-12 17:24 UTC, merged