Update tests
Opentrons/opentrons-emulation pull request #244
Opened 2023-02-23 17:02 UTC by DerekMaggio

# Overview

# Changelog

# Review requests

# Risk assessment

2023-02-27 17:44 UTC, sfoster1 requested changes
Lot here and will take time to review in depth, but I think some of these tests that check every member of a dataclass for a particular value are probably much better off either
 - building a second dataclass and checking that, or
 - comparing asdict() outputs
By doing that, you'll compare everything at the same time and avoid early failures obscuring later ones, and also get nice diff output.

2023-02-27 17:44 UTC, sfoster1 commented on emulation_system/tests/compose_file_creator/conversion_logic/service_builders/test_concrete_emulator_proxy_service_builder.py
>      assert service.container_name == "emulator-proxy"
Tests like this, that assert a whole bunch of member values are equal to some value, are probably better off using a process like:
- Turn the object into a dict
- Compare the dict to a similar dict containing the items you want

This is a little removed from comparing the objects directly, but what it does mean is that pytest will actually print a diff of everything at once - no early failures obscuring later failures, everything side-by-side.

2023-03-06 16:12 UTC, DerekMaggio commented on emulation_system/tests/compose_file_creator/conversion_logic/service_builders/test_concrete_emulator_proxy_service_builder.py
>      assert service.container_name == "emulator-proxy"
@sfoster1, are you good if I fix this in a followup PR? 
While I totally agree that your suggestion is better, it's been like this for a while.
I would rather fix after everything is merged because rebasing these stacked changes is a nightmare.

2023-03-06 16:16 UTC, sfoster1 commented on emulation_system/tests/compose_file_creator/conversion_logic/service_builders/test_concrete_emulator_proxy_service_builder.py
>      assert service.container_name == "emulator-proxy"
Yeah sounds good. Definitely do it though, it will be great

2023-03-06 16:17 UTC, sfoster1 approved these changes

2023-03-06 16:26 UTC, merged