Extra mounts
Opentrons/opentrons-emulation pull request #276
Opened 2023-07-24 19:16 UTC by DerekMaggio

# Overview

# Changelog

# Review requests

# Risk assessment

2023-07-24 19:42 UTC, DerekMaggio commented
Going to add logic to throw an exception if container name specified in mount does not exist in created docker compose file

2023-07-24 20:19 UTC, DerekMaggio commented
> Going to add logic to throw an exception if container name specified in mount does not exist in created docker compose file.
> 
> Do not approve without it

https://github.com/Opentrons/opentrons-emulation/pull/276/commits/c0e4eab5b5ddf54093b7c7513f42a68f63ba333c

2023-07-24 20:20 UTC, DerekMaggio commented
> Going to add logic to throw an exception if container name specified in mount does not exist in created docker compose file.
> 
> Do not approve without it

https://github.com/Opentrons/opentrons-emulation/pull/276/commits/c0e4eab5b5ddf54093b7c7513f42a68f63ba333c

2023-07-24 20:49 UTC, DerekMaggio commented
Updates to wiki here:
https://github.com/Opentrons/opentrons-emulation/wiki/Configuration-File/c2fd2c7e04e1dd8c854ea4d2af573911a77f1fb3

2023-07-25 16:42 UTC, sfoster1 requested changes
Let's change those default paths, but looks good otherwise!

2023-07-25 16:42 UTC, sfoster1 commented on samples/ot3/ot3_local_with_custom_mounts.yaml
> +ot3-firmware-source: /home/derek-maggio/Documents/repos/ot3-firmware
let's set these to something like `/make/this/path/something/that/exists` so you get to see it really quickly from the error message

2023-07-25 16:51 UTC, DerekMaggio commented on samples/ot3/ot3_local_with_custom_mounts.yaml
> +ot3-firmware-source: /home/derek-maggio/Documents/repos/ot3-firmware
Ooops that is what is had been then I overwrote it by accident.
Thank you

2023-07-25 16:53 UTC, DerekMaggio commented on samples/ot3/ot3_local_with_custom_mounts.yaml
> +ot3-firmware-source: /home/derek-maggio/Documents/repos/ot3-firmware
https://github.com/Opentrons/opentrons-emulation/pull/276/commits/6a2c0f613111c3c69ebe32b56ac4a006595b1c97

2023-07-25 16:54 UTC, merged