Parse input to compose file version ret 394
Opentrons/opentrons-emulation pull request #49
Opened 2022-01-07 21:26 UTC by DerekMaggio

# Overview

# Changelog

# Review requests

# Risk assessment

2022-01-10 21:54 UTC, amitlissack commented on emulation_system/emulation_system/compose_file_creator/conversion_layer.py
> +    def add_ports(self) -> None:
What are the inputs to the `add` methods?

2022-01-10 21:55 UTC, DerekMaggio commented on emulation_system/emulation_system/compose_file_creator/conversion_layer.py
> +    def add_ports(self) -> None:
These are just placeholders for right now. I am working on them in a separate PR

2022-01-10 21:55 UTC, DerekMaggio commented on emulation_system/emulation_system/compose_file_creator/conversion_layer.py
> +    def add_ports(self) -> None:
They will actually end up being private methods

2022-01-11 13:51 UTC, sfoster1 requested changes
Uh I put my big comment inline sorry but let's center this code on the data model and have free, pure functions for the translation layer.

2022-01-11 13:51 UTC, sfoster1 commented on emulation_system/emulation_system/compose_file_creator/conversion_layer.py
> +    def add_ports(self) -> None:
From a style perspective, I tend not to like methods like this in Python. They bring to mind the [builder pattern](https://en.wikipedia.org/wiki/Builder_pattern), a pattern that really took off in java because of the lack of 1) easy to create mapping primitives 2) named arguments - it was basically the only way to have a bag-of-data or configuration-heavy class constructor where you wouldn't have to like have the class def up in another window and be following the positional arguments with your finger.

The downside to the pattern is that it's very hard to programmatically assess when you're done building a class, and what the type of intermediates in the builder chain is. If the way you build this class looks like this:
```
dockerfile = ConversionLayer().add_ports(...).add_env_vars(...).add...
```

What's the type of the intermediates between the chain calls? (and even if you're separating those to different lines, the same thing applies).

Even if those methods are private and called by the initializer, if they're setting private members inside the methods then it's hard for static analysis like mypy to figure out what should be present and when. It also makes it hard to make this bag-of-data class non-mutable.

I'd advocate for instead doing this architectural pattern:

- Have a model for the emulator stack consisting of some set of dataclass types, probably frozen but maybe not. This model is the One True Internal Representation.
- Have adapters or conversion layers that can ingest from / export to docker-compose files, emulator stack config files, etc etc

Basically, put the data and the data model at the center and model the transformers as pure functions - inputs and outputs, no state - that operate on the data model. At that point, things become easier to test, easier to type, and easier to read.

2022-01-11 15:05 UTC, DerekMaggio commented on emulation_system/emulation_system/compose_file_creator/conversion_layer.py
> +    def add_ports(self) -> None:
> Have adapters or conversion layers that can ingest from / export to docker-compose files, emulator stack config files, etc etc

Does this mean that I should not have intermediary layers?

2022-01-11 22:10 UTC, DerekMaggio commented on emulation_system/emulation_system/compose_file_creator/conversion_layer.py
> +    def add_ports(self) -> None:
@sfoster1 check out my latest commit and let me know what you think.

2022-01-13 15:58 UTC, sfoster1 approved these changes
Nice, this looks really solid!

2022-01-13 16:02 UTC, merged